// Generated by gencpp from file robot_msgs/SpeekRequest.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_SPEEKREQUEST_H
#define ROBOT_MSGS_MESSAGE_SPEEKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct SpeekRequest_
{
  typedef SpeekRequest_<ContainerAllocator> Type;

  SpeekRequest_()
    : id(0)
    , type(0)
    , arg1()
    , arg2()  {
    }
  SpeekRequest_(const ContainerAllocator& _alloc)
    : id(0)
    , type(0)
    , arg1(_alloc)
    , arg2(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef uint8_t _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _arg1_type;
  _arg1_type arg1;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _arg2_type;
  _arg2_type arg2;




  typedef boost::shared_ptr< ::robot_msgs::SpeekRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::SpeekRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SpeekRequest_

typedef ::robot_msgs::SpeekRequest_<std::allocator<void> > SpeekRequest;

typedef boost::shared_ptr< ::robot_msgs::SpeekRequest > SpeekRequestPtr;
typedef boost::shared_ptr< ::robot_msgs::SpeekRequest const> SpeekRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::SpeekRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::SpeekRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'robot_msgs': ['/home/renxl/share/catkin_ws/src/ihome/robot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::SpeekRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::SpeekRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::SpeekRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::SpeekRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::SpeekRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::SpeekRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::SpeekRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e65633c461c2612af19a09955e426447";
  }

  static const char* value(const ::robot_msgs::SpeekRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe65633c461c2612aULL;
  static const uint64_t static_value2 = 0xf19a09955e426447ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::SpeekRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/SpeekRequest";
  }

  static const char* value(const ::robot_msgs::SpeekRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::SpeekRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n\
uint8 type\n\
string arg1\n\
string arg2\n\
";
  }

  static const char* value(const ::robot_msgs::SpeekRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::SpeekRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.type);
      stream.next(m.arg1);
      stream.next(m.arg2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpeekRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::SpeekRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::SpeekRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "arg1: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.arg1);
    s << indent << "arg2: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.arg2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_SPEEKREQUEST_H
