/** CAN message encoder/decoder: automatically generated - do not edit
  * Generated by dbcc: See https://github.com/howerj/dbcc */
#ifndef ARS408_CAN_DATABASE_CH4_H
#define ARS408_CAN_DATABASE_CH4_H

#include <stdint.h>
#include <stdio.h>

#ifdef __cplusplus
extern "C" { 
#endif

#ifndef PREPACK
#define PREPACK
#endif

#ifndef POSTPACK
#define POSTPACK
#endif

#ifndef DBCC_TIME_STAMP
#define DBCC_TIME_STAMP
typedef uint32_t dbcc_time_stamp_t; /* Time stamp for message; you decide on units */
#endif

#ifndef DBCC_STATUS_ENUM
#define DBCC_STATUS_ENUM
typedef enum {
	DBCC_SIG_STAT_UNINITIALIZED_E = 0, /* Message never sent/received */
	DBCC_SIG_STAT_OK_E            = 1, /* Message ok */
	DBCC_SIG_STAT_ERROR_E         = 2, /* Encode/Decode/Timestamp/Any error */
} dbcc_signal_status_e;
#endif

typedef PREPACK struct {
	uint8_t CollDetRelayCtrl_Param; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x008_CollDetRelayCtrl_t_ch4;

typedef PREPACK struct {
	uint16_t RadarCfg_MaxDistance; /* scaling 2.0, offset 0.0, units m  */
	uint8_t RadarCfg_SensorID; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarCfg_RadarPower; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarCfg_SortIndex; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarCfg_RCS_Threshold; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarCfg_OutputType; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarCfg_MaxDistance_valid; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarCfg_SensorID_valid; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarCfg_RadarPower_valid; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarCfg_OutputType_valid; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarCfg_SendQuality_valid; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarCfg_SendExtInfo_valid; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarCfg_SortIndex_valid; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarCfg_StoreInNVM_valid; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarCfg_CtrlRelay_valid; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarCfg_CtrlRelay; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarCfg_SendQuality; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarCfg_SendExtInfo; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarCfg_StoreInNVM; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarCfg_RCS_Threshold_Valid; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x240_RadarConfiguration4_t;

typedef PREPACK struct {
	uint16_t RadarState_MaxDistanceCfg; /* scaling 2.0, offset 0.0, units none  */
	uint8_t RadarState_RadarPowerCfg; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarState_SensorID; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarState_SortIndex; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarState_RCS_Threshold; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarState_OutputTypeCfg; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarState_MotionRxState; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarState_NVMReadStatus; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarState_NVMwriteStatus; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarState_CtrlRelayCfg; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarState_SendQualityCfg; /* scaling 1.0, offset 0.0, units none  */
	uint8_t RadarState_SendExtInfoCfg; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x241_RadarState4_t;

typedef PREPACK struct {
	uint16_t FilterCfg_Min_X; /* scaling 0.2, offset -500.0, units m  */
	uint16_t FilterCfg_Max_X; /* scaling 0.2, offset -500.0, units m  */
	uint16_t FilterCfg_Min_Y; /* scaling 0.2, offset -409.5, units m  */
	uint16_t FilterCfg_Min_VYRightLeft; /* scaling 0.0, offset 0.0, units m/s  */
	uint16_t FilterCfg_Min_VYLeftRight; /* scaling 0.0, offset 0.0, units m/s  */
	uint16_t FilterCfg_Min_VXOncome; /* scaling 0.0, offset 0.0, units m/s  */
	uint16_t FilterCfg_Min_VXDepart; /* scaling 0.0, offset 0.0, units m/s  */
	uint16_t FilterCfg_Min_VrelOncome; /* scaling 0.0, offset 0.0, units m/s  */
	uint16_t FilterCfg_Min_VrelDepart; /* scaling 0.0, offset 0.0, units m/s  */
	uint16_t FilterCfg_Min_Size; /* scaling 0.0, offset 0.0, units m2  */
	uint16_t FilterCfg_Min_RCS; /* scaling 0.0, offset -50.0, units dB  */
	uint16_t FilterCfg_Min_ProbExists; /* scaling 1.0, offset 0.0, units none  */
	uint16_t FilterCfg_Min_Lifetime; /* scaling 0.1, offset 0.0, units s  */
	uint16_t FilterCfg_Min_Azimuth; /* scaling 0.0, offset -50.0, units deg  */
	uint16_t FilterCfg_Min_NofObj; /* scaling 1.0, offset 0.0, units none  */
	uint16_t FilterCfg_Min_Distance; /* scaling 0.1, offset 0.0, units m  */
	uint16_t FilterCfg_Max_Y; /* scaling 0.2, offset -409.5, units m  */
	uint16_t FilterCfg_Max_VYRightLeft; /* scaling 0.0, offset 0.0, units m/s  */
	uint16_t FilterCfg_Max_VXOncome; /* scaling 0.0, offset 0.0, units m/s  */
	uint16_t FilterCfg_Max_VYLeftRight; /* scaling 0.0, offset 0.0, units m/s  */
	uint16_t FilterCfg_Max_VXDepart; /* scaling 0.0, offset 0.0, units m/s  */
	uint16_t FilterCfg_Max_VrelOncome; /* scaling 0.0, offset 0.0, units m/s  */
	uint16_t FilterCfg_Max_VrelDepart; /* scaling 0.0, offset 0.0, units m/s  */
	uint16_t FilterCfg_Max_Size; /* scaling 0.0, offset 0.0, units m2  */
	uint16_t FilterCfg_Max_RCS; /* scaling 0.0, offset -50.0, units dB  */
	uint16_t FilterCfg_Max_ProbExists; /* scaling 1.0, offset 0.0, units none  */
	uint16_t FilterCfg_Max_NofObj; /* scaling 1.0, offset 0.0, units none  */
	uint16_t FilterCfg_Max_Lifetime; /* scaling 0.1, offset 0.0, units s  */
	uint16_t FilterCfg_Max_Distance; /* scaling 0.1, offset 0.0, units m  */
	uint16_t FilterCfg_Max_Azimuth; /* scaling 0.0, offset -50.0, units deg  */
	uint8_t FilterCfg_Index; /* scaling 1.0, offset 0.0, units none  */
	uint8_t FilterCfg_Valid; /* scaling 1.0, offset 0.0, units none  */
	uint8_t FilterCfg_Active; /* scaling 1.0, offset 0.0, units none  */
	uint8_t FilterCfg_Type; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x242_FilterCfg4_t;

typedef PREPACK struct {
	uint8_t FilterState_NofClusterFilterCfg; /* scaling 1.0, offset 0.0, units none  */
	uint8_t FilterState_NofObjectFilterCfg; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x243_FilterState_Header4_t;

typedef PREPACK struct {
	uint16_t FilterState_Min_X; /* scaling 0.2, offset -500.0, units m  */
	uint16_t FilterState_Max_X; /* scaling 0.2, offset -500.0, units m  */
	uint16_t FilterState_Min_Y; /* scaling 0.2, offset -409.5, units m  */
	uint16_t FilterState_Min_VYRightLeft; /* scaling 0.0, offset 0.0, units m/s  */
	uint16_t FilterState_Min_VYLeftRight; /* scaling 0.0, offset 0.0, units m/s  */
	uint16_t FilterState_Min_VXOncome; /* scaling 0.0, offset 0.0, units m/s  */
	uint16_t FilterState_Min_VXDepart; /* scaling 0.0, offset 0.0, units m/s  */
	uint16_t FilterState_Min_VrelOncome; /* scaling 0.0, offset 0.0, units m/s  */
	uint16_t FilterState_Min_VrelDepart; /* scaling 0.0, offset 0.0, units m/s  */
	uint16_t FilterState_Min_Size; /* scaling 0.0, offset 0.0, units m2  */
	uint16_t FilterState_Min_RCS; /* scaling 0.0, offset -50.0, units dB  */
	uint16_t FilterState_Min_ProbExists; /* scaling 1.0, offset 0.0, units none  */
	uint16_t FilterState_Min_NofObj; /* scaling 1.0, offset 0.0, units none  */
	uint16_t FilterState_Min_Lifetime; /* scaling 0.1, offset 0.0, units s  */
	uint16_t FilterState_Min_Distance; /* scaling 0.1, offset 0.0, units m  */
	uint16_t FilterState_Min_Azimuth; /* scaling 0.0, offset -50.0, units deg  */
	uint16_t FilterState_Max_Y; /* scaling 0.2, offset -409.5, units m  */
	uint16_t FilterState_Max_VYRightLeft; /* scaling 0.0, offset 0.0, units m/s  */
	uint16_t FilterState_Max_VYLeftRight; /* scaling 0.0, offset 0.0, units m/s  */
	uint16_t FilterState_Max_VXOncome; /* scaling 0.0, offset 0.0, units m/s  */
	uint16_t FilterState_Max_VXDepart; /* scaling 0.0, offset 0.0, units m/s  */
	uint16_t FilterState_Max_VrelOncome; /* scaling 0.0, offset 0.0, units m/s  */
	uint16_t FilterState_Max_VrelDepart; /* scaling 0.0, offset 0.0, units m/s  */
	uint16_t FilterState_Max_Size; /* scaling 0.0, offset 0.0, units m2  */
	uint16_t FilterState_Max_RCS; /* scaling 0.0, offset -50.0, units dB  */
	uint16_t FilterState_Max_ProbExists; /* scaling 1.0, offset 0.0, units none  */
	uint16_t FilterState_Max_NofObj; /* scaling 1.0, offset 0.0, units none  */
	uint16_t FilterState_Max_Lifetime; /* scaling 0.1, offset 0.0, units s  */
	uint16_t FilterState_Max_Distance; /* scaling 0.1, offset 0.0, units m  */
	uint16_t FilterState_Max_Azimuth; /* scaling 0.0, offset -50.0, units deg  */
	uint8_t FilterState_Index; /* scaling 1.0, offset 0.0, units none  */
	uint8_t FilterState_Active; /* scaling 1.0, offset 0.0, units none  */
	uint8_t FilterState_Type; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x244_FilterState_Cfg4_t;

typedef PREPACK struct {
	uint16_t RadarDevice_Speed; /* scaling 0.0, offset 0.0, units m/s  */
	uint8_t RadarDevice_SpeedDirection; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x340_SpeedInformation4_t;

typedef PREPACK struct {
	uint16_t RadarDevice_YawRate; /* scaling 0.0, offset -327.7, units �/s  */
} POSTPACK can_0x341_YawRateInformation4_t;

typedef PREPACK struct {
	uint8_t CollDetCfg_MinDetectTime; /* scaling 0.1, offset 0.0, units s  */
	uint8_t CollDetCfg_WarningReset; /* scaling 1.0, offset 0.0, units none  */
	uint8_t CollDetCfg_Activate; /* scaling 1.0, offset 0.0, units none  */
	uint8_t CollDetCfg_MinTime_valid; /* scaling 1.0, offset 0.0, units none  */
	uint8_t CollDetCfg_ClearRegions; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x440_CollDetCfg4_t;

typedef PREPACK struct {
	uint16_t CollDetRegCfg_Point1X; /* scaling 0.2, offset -500.0, units m  */
	uint16_t CollDetRegCfg_Point2X; /* scaling 0.2, offset -500.0, units m  */
	uint16_t CollDetRegCfg_Point1Y; /* scaling 0.2, offset -204.6, units m  */
	uint16_t CollDetRegCfg_Point2Y; /* scaling 0.2, offset -204.6, units m  */
	uint8_t CollDetRegCfg_RegionID; /* scaling 1.0, offset 0.0, units none  */
	uint8_t CollDetRegCfg_Activate; /* scaling 1.0, offset 0.0, units none  */
	uint8_t CollDetRegCfg_Coordinates_valid; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x441_CollDetRegionCfg4_t;

typedef PREPACK struct {
	uint16_t CollDetRegState_Point1X; /* scaling 0.2, offset -500.0, units m  */
	uint16_t CollDetRegState_Point2X; /* scaling 0.2, offset -500.0, units m  */
	uint16_t CollDetRegState_Point1Y; /* scaling 0.2, offset -204.6, units m  */
	uint16_t CollDetRegState_Point2Y; /* scaling 0.2, offset -204.6, units m  */
	uint8_t CollDetRegState_NofObjects; /* scaling 1.0, offset 0.0, units none  */
	uint8_t CollDetRegState_RegionID; /* scaling 1.0, offset 0.0, units none  */
	uint8_t CollDetRegState_WarningLevel; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x442_CollDetRegionState4_t;

typedef PREPACK struct {
	uint16_t CollDetState_MeasCounter; /* scaling 1.0, offset 0.0, units none  */
	uint8_t CollDetState_MinDetectTime; /* scaling 0.1, offset 0.0, units s  */
	uint8_t CollDetState_NofRegions; /* scaling 1.0, offset 0.0, units none  */
	uint8_t CollDetState_Active; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x448_CollDetState4_t;

typedef PREPACK struct {
	uint16_t Cluster_MeasCounter; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Cluster_NofClustersNear; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Cluster_NofClustersFar; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Cluster_InterfaceVersion; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x640_Cluster_0_Status4_t;

typedef PREPACK struct {
	uint16_t Obj_MeasCounter; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Obj_NofObjects; /* scaling 1.0, offset 0.0, units 1  */
	uint8_t Obj_InterfaceVersion; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x64a_Obj_0_Status4_t;

typedef PREPACK struct {
	uint16_t Obj_DistLong; /* scaling 0.2, offset -500.0, units m  */
	uint16_t Obj_DistLat; /* scaling 0.2, offset -204.6, units m  */
	uint16_t Obj_VrelLong; /* scaling 0.2, offset -128.0, units m/s  */
	uint16_t Obj_VrelLat; /* scaling 0.2, offset -64.0, units m/s  */
	uint8_t Obj_ID; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Obj_RCS; /* scaling 0.5, offset -64.0, units dBm�  */
	uint8_t Obj_DynProp; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x64b_Obj_1_General4_t;

typedef PREPACK struct {
	uint8_t Obj_ID; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Obj_DistLat_rms; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Obj_DistLong_rms; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Obj_VrelLat_rms; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Obj_VrelLong_rms; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Obj_ArelLong_rms; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Obj_Orientation_rms; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Obj_ArelLat_rms; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Obj_MeasState; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Obj_ProbOfExist; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x64c_Obj_2_Quality4_t;

typedef PREPACK struct {
	uint16_t Obj_ArelLong; /* scaling 0.0, offset -10.0, units m/s�  */
	uint16_t Obj_OrientationAngle; /* scaling 0.4, offset -180.0, units deg  */
	uint16_t Obj_ArelLat; /* scaling 0.0, offset -2.5, units m/s�  */
	uint8_t Obj_ID; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Obj_Length; /* scaling 0.2, offset 0.0, units m  */
	uint8_t Obj_Width; /* scaling 0.2, offset 0.0, units m  */
	uint8_t Obj_Class; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x64d_Obj_3_Extended4_t;

typedef PREPACK struct {
	uint8_t Obj_ID; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Obj_CollDetRegionBitfield; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x64e_Obj_4_Warning4_t;

typedef PREPACK struct {
	uint8_t Version_MajorRelease; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Version_MinorRelease; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Version_PatchLevel; /* scaling 1.0, offset 0.0, units none  */
} POSTPACK can_0x740_VersionID4_t;

typedef PREPACK struct {
	uint16_t Cluster_DistLong; /* scaling 0.2, offset -500.0, units m  */
	uint16_t Cluster_DistLat; /* scaling 0.2, offset -102.3, units m  */
	uint16_t Cluster_VrelLong; /* scaling 0.2, offset -128.0, units m/s  */
	uint16_t Cluster_VrelLat; /* scaling 0.2, offset -64.0, units m/s  */
	uint8_t Cluster_ID; /* scaling 1.0, offset 0.0, units 1  */
	uint8_t Cluster_RCS; /* scaling 0.5, offset -64.0, units dBm�  */
	uint8_t Cluster_DynProp; /* scaling 1.0, offset 0.0, units 1  */
} POSTPACK can_0x741_Cluster_1_General4_t;

typedef PREPACK struct {
	uint8_t Cluster_ID; /* scaling 1.0, offset 0.0, units 1  */
	uint8_t Cluster_DistLat_rms; /* scaling 1.0, offset 0.0, units m  */
	uint8_t Cluster_DistLong_rms; /* scaling 1.0, offset 0.0, units m  */
	uint8_t Cluster_VrelLat_rms; /* scaling 1.0, offset 0.0, units m/s  */
	uint8_t Cluster_VrelLong_rms; /* scaling 1.0, offset 0.0, units m/s  */
	uint8_t Cluster_InvalidState; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Cluster_PdH0; /* scaling 1.0, offset 0.0, units none  */
	uint8_t Cluster_AmbigState; /* scaling 1.0, offset 0.0, units 1  */
} POSTPACK can_0x742_Cluster_2_Quality4_t;

typedef PREPACK struct {
	dbcc_time_stamp_t can_0x008_CollDetRelayCtrl_time_stamp_rx;
	dbcc_time_stamp_t can_0x240_RadarConfiguration4_time_stamp_rx;
	dbcc_time_stamp_t can_0x241_RadarState4_time_stamp_rx;
	dbcc_time_stamp_t can_0x242_FilterCfg4_time_stamp_rx;
	dbcc_time_stamp_t can_0x243_FilterState_Header4_time_stamp_rx;
	dbcc_time_stamp_t can_0x244_FilterState_Cfg4_time_stamp_rx;
	dbcc_time_stamp_t can_0x340_SpeedInformation4_time_stamp_rx;
	dbcc_time_stamp_t can_0x341_YawRateInformation4_time_stamp_rx;
	dbcc_time_stamp_t can_0x440_CollDetCfg4_time_stamp_rx;
	dbcc_time_stamp_t can_0x441_CollDetRegionCfg4_time_stamp_rx;
	dbcc_time_stamp_t can_0x442_CollDetRegionState4_time_stamp_rx;
	dbcc_time_stamp_t can_0x448_CollDetState4_time_stamp_rx;
	dbcc_time_stamp_t can_0x640_Cluster_0_Status4_time_stamp_rx;
	dbcc_time_stamp_t can_0x64a_Obj_0_Status4_time_stamp_rx;
	dbcc_time_stamp_t can_0x64b_Obj_1_General4_time_stamp_rx;
	dbcc_time_stamp_t can_0x64c_Obj_2_Quality4_time_stamp_rx;
	dbcc_time_stamp_t can_0x64d_Obj_3_Extended4_time_stamp_rx;
	dbcc_time_stamp_t can_0x64e_Obj_4_Warning4_time_stamp_rx;
	dbcc_time_stamp_t can_0x740_VersionID4_time_stamp_rx;
	dbcc_time_stamp_t can_0x741_Cluster_1_General4_time_stamp_rx;
	dbcc_time_stamp_t can_0x742_Cluster_2_Quality4_time_stamp_rx;
	unsigned can_0x008_CollDetRelayCtrl_status : 2;
	unsigned can_0x008_CollDetRelayCtrl_tx : 1;
	unsigned can_0x008_CollDetRelayCtrl_rx : 1;
	unsigned can_0x240_RadarConfiguration4_status : 2;
	unsigned can_0x240_RadarConfiguration4_tx : 1;
	unsigned can_0x240_RadarConfiguration4_rx : 1;
	unsigned can_0x241_RadarState4_status : 2;
	unsigned can_0x241_RadarState4_tx : 1;
	unsigned can_0x241_RadarState4_rx : 1;
	unsigned can_0x242_FilterCfg4_status : 2;
	unsigned can_0x242_FilterCfg4_tx : 1;
	unsigned can_0x242_FilterCfg4_rx : 1;
	unsigned can_0x243_FilterState_Header4_status : 2;
	unsigned can_0x243_FilterState_Header4_tx : 1;
	unsigned can_0x243_FilterState_Header4_rx : 1;
	unsigned can_0x244_FilterState_Cfg4_status : 2;
	unsigned can_0x244_FilterState_Cfg4_tx : 1;
	unsigned can_0x244_FilterState_Cfg4_rx : 1;
	unsigned can_0x340_SpeedInformation4_status : 2;
	unsigned can_0x340_SpeedInformation4_tx : 1;
	unsigned can_0x340_SpeedInformation4_rx : 1;
	unsigned can_0x341_YawRateInformation4_status : 2;
	unsigned can_0x341_YawRateInformation4_tx : 1;
	unsigned can_0x341_YawRateInformation4_rx : 1;
	unsigned can_0x440_CollDetCfg4_status : 2;
	unsigned can_0x440_CollDetCfg4_tx : 1;
	unsigned can_0x440_CollDetCfg4_rx : 1;
	unsigned can_0x441_CollDetRegionCfg4_status : 2;
	unsigned can_0x441_CollDetRegionCfg4_tx : 1;
	unsigned can_0x441_CollDetRegionCfg4_rx : 1;
	unsigned can_0x442_CollDetRegionState4_status : 2;
	unsigned can_0x442_CollDetRegionState4_tx : 1;
	unsigned can_0x442_CollDetRegionState4_rx : 1;
	unsigned can_0x448_CollDetState4_status : 2;
	unsigned can_0x448_CollDetState4_tx : 1;
	unsigned can_0x448_CollDetState4_rx : 1;
	unsigned can_0x640_Cluster_0_Status4_status : 2;
	unsigned can_0x640_Cluster_0_Status4_tx : 1;
	unsigned can_0x640_Cluster_0_Status4_rx : 1;
	unsigned can_0x64a_Obj_0_Status4_status : 2;
	unsigned can_0x64a_Obj_0_Status4_tx : 1;
	unsigned can_0x64a_Obj_0_Status4_rx : 1;
	unsigned can_0x64b_Obj_1_General4_status : 2;
	unsigned can_0x64b_Obj_1_General4_tx : 1;
	unsigned can_0x64b_Obj_1_General4_rx : 1;
	unsigned can_0x64c_Obj_2_Quality4_status : 2;
	unsigned can_0x64c_Obj_2_Quality4_tx : 1;
	unsigned can_0x64c_Obj_2_Quality4_rx : 1;
	unsigned can_0x64d_Obj_3_Extended4_status : 2;
	unsigned can_0x64d_Obj_3_Extended4_tx : 1;
	unsigned can_0x64d_Obj_3_Extended4_rx : 1;
	unsigned can_0x64e_Obj_4_Warning4_status : 2;
	unsigned can_0x64e_Obj_4_Warning4_tx : 1;
	unsigned can_0x64e_Obj_4_Warning4_rx : 1;
	unsigned can_0x740_VersionID4_status : 2;
	unsigned can_0x740_VersionID4_tx : 1;
	unsigned can_0x740_VersionID4_rx : 1;
	unsigned can_0x741_Cluster_1_General4_status : 2;
	unsigned can_0x741_Cluster_1_General4_tx : 1;
	unsigned can_0x741_Cluster_1_General4_rx : 1;
	unsigned can_0x742_Cluster_2_Quality4_status : 2;
	unsigned can_0x742_Cluster_2_Quality4_tx : 1;
	unsigned can_0x742_Cluster_2_Quality4_rx : 1;
	can_0x008_CollDetRelayCtrl_t_ch4 can_0x008_CollDetRelayCtrl;
	can_0x240_RadarConfiguration4_t can_0x240_RadarConfiguration4;
	can_0x241_RadarState4_t can_0x241_RadarState4;
	can_0x242_FilterCfg4_t can_0x242_FilterCfg4;
	can_0x243_FilterState_Header4_t can_0x243_FilterState_Header4;
	can_0x244_FilterState_Cfg4_t can_0x244_FilterState_Cfg4;
	can_0x340_SpeedInformation4_t can_0x340_SpeedInformation4;
	can_0x341_YawRateInformation4_t can_0x341_YawRateInformation4;
	can_0x440_CollDetCfg4_t can_0x440_CollDetCfg4;
	can_0x441_CollDetRegionCfg4_t can_0x441_CollDetRegionCfg4;
	can_0x442_CollDetRegionState4_t can_0x442_CollDetRegionState4;
	can_0x448_CollDetState4_t can_0x448_CollDetState4;
	can_0x640_Cluster_0_Status4_t can_0x640_Cluster_0_Status4;
	can_0x64a_Obj_0_Status4_t can_0x64a_Obj_0_Status4;
	can_0x64b_Obj_1_General4_t can_0x64b_Obj_1_General4;
	can_0x64c_Obj_2_Quality4_t can_0x64c_Obj_2_Quality4;
	can_0x64d_Obj_3_Extended4_t can_0x64d_Obj_3_Extended4;
	can_0x64e_Obj_4_Warning4_t can_0x64e_Obj_4_Warning4;
	can_0x740_VersionID4_t can_0x740_VersionID4;
	can_0x741_Cluster_1_General4_t can_0x741_Cluster_1_General4;
	can_0x742_Cluster_2_Quality4_t can_0x742_Cluster_2_Quality4;
} POSTPACK can_obj_ars408_can_database_ch4_h_t;

int unpack_message_ch4(can_obj_ars408_can_database_ch4_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp);
int pack_message_ch4(can_obj_ars408_can_database_ch4_h_t *o, const unsigned long id, uint64_t *data);
int print_message_ch4(const can_obj_ars408_can_database_ch4_h_t *o, const unsigned long id, FILE *output);

int decode_can_0x008_CollDetRelayCtrl_Param_ch4(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x008_CollDetRelayCtrl_Param_ch4(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);


int decode_can_0x240_RadarCfg_MaxDistance(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x240_RadarCfg_MaxDistance(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x240_RadarCfg_SensorID(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x240_RadarCfg_SensorID(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x240_RadarCfg_RadarPower(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x240_RadarCfg_RadarPower(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x240_RadarCfg_SortIndex(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x240_RadarCfg_SortIndex(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x240_RadarCfg_RCS_Threshold(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x240_RadarCfg_RCS_Threshold(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x240_RadarCfg_OutputType(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x240_RadarCfg_OutputType(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x240_RadarCfg_MaxDistance_valid(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x240_RadarCfg_MaxDistance_valid(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x240_RadarCfg_SensorID_valid(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x240_RadarCfg_SensorID_valid(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x240_RadarCfg_RadarPower_valid(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x240_RadarCfg_RadarPower_valid(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x240_RadarCfg_OutputType_valid(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x240_RadarCfg_OutputType_valid(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x240_RadarCfg_SendQuality_valid(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x240_RadarCfg_SendQuality_valid(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x240_RadarCfg_SendExtInfo_valid(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x240_RadarCfg_SendExtInfo_valid(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x240_RadarCfg_SortIndex_valid(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x240_RadarCfg_SortIndex_valid(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x240_RadarCfg_StoreInNVM_valid(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x240_RadarCfg_StoreInNVM_valid(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x240_RadarCfg_CtrlRelay_valid(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x240_RadarCfg_CtrlRelay_valid(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x240_RadarCfg_CtrlRelay(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x240_RadarCfg_CtrlRelay(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x240_RadarCfg_SendQuality(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x240_RadarCfg_SendQuality(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x240_RadarCfg_SendExtInfo(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x240_RadarCfg_SendExtInfo(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x240_RadarCfg_StoreInNVM(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x240_RadarCfg_StoreInNVM(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x240_RadarCfg_RCS_Threshold_Valid(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x240_RadarCfg_RCS_Threshold_Valid(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);


int decode_can_0x241_RadarState_MaxDistanceCfg(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x241_RadarState_MaxDistanceCfg(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x241_RadarState_RadarPowerCfg(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x241_RadarState_RadarPowerCfg(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x241_RadarState_SensorID(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x241_RadarState_SensorID(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x241_RadarState_SortIndex(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x241_RadarState_SortIndex(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x241_RadarState_RCS_Threshold(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x241_RadarState_RCS_Threshold(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x241_RadarState_OutputTypeCfg(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x241_RadarState_OutputTypeCfg(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x241_RadarState_MotionRxState(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x241_RadarState_MotionRxState(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x241_RadarState_NVMReadStatus(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x241_RadarState_NVMReadStatus(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x241_RadarState_NVMwriteStatus(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x241_RadarState_NVMwriteStatus(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x241_RadarState_CtrlRelayCfg(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x241_RadarState_CtrlRelayCfg(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x241_RadarState_SendQualityCfg(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x241_RadarState_SendQualityCfg(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x241_RadarState_SendExtInfoCfg(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x241_RadarState_SendExtInfoCfg(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);


int decode_can_0x242_FilterCfg_Min_X(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Min_X(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Max_X(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Max_X(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Min_Y(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Min_Y(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Min_VYRightLeft(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Min_VYRightLeft(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Min_VYLeftRight(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Min_VYLeftRight(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Min_VXOncome(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Min_VXOncome(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Min_VXDepart(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Min_VXDepart(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Min_VrelOncome(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Min_VrelOncome(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Min_VrelDepart(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Min_VrelDepart(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Min_Size(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Min_Size(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Min_RCS(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Min_RCS(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Min_ProbExists(const can_obj_ars408_can_database_ch4_h_t *o, uint16_t *out);
int encode_can_0x242_FilterCfg_Min_ProbExists(can_obj_ars408_can_database_ch4_h_t *o, uint16_t in);
int decode_can_0x242_FilterCfg_Min_Lifetime(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Min_Lifetime(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Min_Azimuth(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Min_Azimuth(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Min_NofObj(const can_obj_ars408_can_database_ch4_h_t *o, uint16_t *out);
int encode_can_0x242_FilterCfg_Min_NofObj(can_obj_ars408_can_database_ch4_h_t *o, uint16_t in);
int decode_can_0x242_FilterCfg_Min_Distance(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Min_Distance(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Max_Y(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Max_Y(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Max_VYRightLeft(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Max_VYRightLeft(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Max_VXOncome(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Max_VXOncome(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Max_VYLeftRight(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Max_VYLeftRight(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Max_VXDepart(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Max_VXDepart(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Max_VrelOncome(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Max_VrelOncome(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Max_VrelDepart(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Max_VrelDepart(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Max_Size(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Max_Size(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Max_RCS(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Max_RCS(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Max_ProbExists(const can_obj_ars408_can_database_ch4_h_t *o, uint16_t *out);
int encode_can_0x242_FilterCfg_Max_ProbExists(can_obj_ars408_can_database_ch4_h_t *o, uint16_t in);
int decode_can_0x242_FilterCfg_Max_NofObj(const can_obj_ars408_can_database_ch4_h_t *o, uint16_t *out);
int encode_can_0x242_FilterCfg_Max_NofObj(can_obj_ars408_can_database_ch4_h_t *o, uint16_t in);
int decode_can_0x242_FilterCfg_Max_Lifetime(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Max_Lifetime(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Max_Distance(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Max_Distance(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Max_Azimuth(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x242_FilterCfg_Max_Azimuth(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x242_FilterCfg_Index(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x242_FilterCfg_Index(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x242_FilterCfg_Valid(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x242_FilterCfg_Valid(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x242_FilterCfg_Active(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x242_FilterCfg_Active(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x242_FilterCfg_Type(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x242_FilterCfg_Type(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);


int decode_can_0x243_FilterState_NofClusterFilterCfg(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x243_FilterState_NofClusterFilterCfg(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x243_FilterState_NofObjectFilterCfg(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x243_FilterState_NofObjectFilterCfg(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);


int decode_can_0x244_FilterState_Min_X(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Min_X(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Max_X(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Max_X(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Min_Y(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Min_Y(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Min_VYRightLeft(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Min_VYRightLeft(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Min_VYLeftRight(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Min_VYLeftRight(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Min_VXOncome(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Min_VXOncome(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Min_VXDepart(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Min_VXDepart(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Min_VrelOncome(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Min_VrelOncome(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Min_VrelDepart(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Min_VrelDepart(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Min_Size(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Min_Size(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Min_RCS(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Min_RCS(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Min_ProbExists(const can_obj_ars408_can_database_ch4_h_t *o, uint16_t *out);
int encode_can_0x244_FilterState_Min_ProbExists(can_obj_ars408_can_database_ch4_h_t *o, uint16_t in);
int decode_can_0x244_FilterState_Min_NofObj(const can_obj_ars408_can_database_ch4_h_t *o, uint16_t *out);
int encode_can_0x244_FilterState_Min_NofObj(can_obj_ars408_can_database_ch4_h_t *o, uint16_t in);
int decode_can_0x244_FilterState_Min_Lifetime(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Min_Lifetime(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Min_Distance(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Min_Distance(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Min_Azimuth(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Min_Azimuth(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Max_Y(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Max_Y(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Max_VYRightLeft(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Max_VYRightLeft(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Max_VYLeftRight(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Max_VYLeftRight(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Max_VXOncome(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Max_VXOncome(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Max_VXDepart(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Max_VXDepart(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Max_VrelOncome(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Max_VrelOncome(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Max_VrelDepart(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Max_VrelDepart(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Max_Size(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Max_Size(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Max_RCS(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Max_RCS(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Max_ProbExists(const can_obj_ars408_can_database_ch4_h_t *o, uint16_t *out);
int encode_can_0x244_FilterState_Max_ProbExists(can_obj_ars408_can_database_ch4_h_t *o, uint16_t in);
int decode_can_0x244_FilterState_Max_NofObj(const can_obj_ars408_can_database_ch4_h_t *o, uint16_t *out);
int encode_can_0x244_FilterState_Max_NofObj(can_obj_ars408_can_database_ch4_h_t *o, uint16_t in);
int decode_can_0x244_FilterState_Max_Lifetime(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Max_Lifetime(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Max_Distance(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Max_Distance(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Max_Azimuth(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x244_FilterState_Max_Azimuth(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x244_FilterState_Index(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x244_FilterState_Index(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x244_FilterState_Active(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x244_FilterState_Active(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x244_FilterState_Type(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x244_FilterState_Type(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);


int decode_can_0x340_RadarDevice_Speed(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x340_RadarDevice_Speed(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x340_RadarDevice_SpeedDirection(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x340_RadarDevice_SpeedDirection(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);


int decode_can_0x341_RadarDevice_YawRate(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x341_RadarDevice_YawRate(can_obj_ars408_can_database_ch4_h_t *o, double in);


int decode_can_0x440_CollDetCfg_MinDetectTime(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x440_CollDetCfg_MinDetectTime(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x440_CollDetCfg_WarningReset(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x440_CollDetCfg_WarningReset(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x440_CollDetCfg_Activate(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x440_CollDetCfg_Activate(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x440_CollDetCfg_MinTime_valid(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x440_CollDetCfg_MinTime_valid(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x440_CollDetCfg_ClearRegions(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x440_CollDetCfg_ClearRegions(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);


int decode_can_0x441_CollDetRegCfg_Point1X(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x441_CollDetRegCfg_Point1X(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x441_CollDetRegCfg_Point2X(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x441_CollDetRegCfg_Point2X(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x441_CollDetRegCfg_Point1Y(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x441_CollDetRegCfg_Point1Y(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x441_CollDetRegCfg_Point2Y(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x441_CollDetRegCfg_Point2Y(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x441_CollDetRegCfg_RegionID(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x441_CollDetRegCfg_RegionID(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x441_CollDetRegCfg_Activate(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x441_CollDetRegCfg_Activate(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x441_CollDetRegCfg_Coordinates_valid(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x441_CollDetRegCfg_Coordinates_valid(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);


int decode_can_0x442_CollDetRegState_Point1X(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x442_CollDetRegState_Point1X(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x442_CollDetRegState_Point2X(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x442_CollDetRegState_Point2X(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x442_CollDetRegState_Point1Y(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x442_CollDetRegState_Point1Y(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x442_CollDetRegState_Point2Y(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x442_CollDetRegState_Point2Y(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x442_CollDetRegState_NofObjects(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x442_CollDetRegState_NofObjects(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x442_CollDetRegState_RegionID(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x442_CollDetRegState_RegionID(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x442_CollDetRegState_WarningLevel(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x442_CollDetRegState_WarningLevel(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);


int decode_can_0x448_CollDetState_MeasCounter(const can_obj_ars408_can_database_ch4_h_t *o, uint16_t *out);
int encode_can_0x448_CollDetState_MeasCounter(can_obj_ars408_can_database_ch4_h_t *o, uint16_t in);
int decode_can_0x448_CollDetState_MinDetectTime(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x448_CollDetState_MinDetectTime(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x448_CollDetState_NofRegions(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x448_CollDetState_NofRegions(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x448_CollDetState_Active(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x448_CollDetState_Active(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);


int decode_can_0x640_Cluster_MeasCounter(const can_obj_ars408_can_database_ch4_h_t *o, uint16_t *out);
int encode_can_0x640_Cluster_MeasCounter(can_obj_ars408_can_database_ch4_h_t *o, uint16_t in);
int decode_can_0x640_Cluster_NofClustersNear(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x640_Cluster_NofClustersNear(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x640_Cluster_NofClustersFar(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x640_Cluster_NofClustersFar(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x640_Cluster_InterfaceVersion(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x640_Cluster_InterfaceVersion(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);


int decode_can_0x64a_Obj_MeasCounter(const can_obj_ars408_can_database_ch4_h_t *o, uint16_t *out);
int encode_can_0x64a_Obj_MeasCounter(can_obj_ars408_can_database_ch4_h_t *o, uint16_t in);
int decode_can_0x64a_Obj_NofObjects(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x64a_Obj_NofObjects(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x64a_Obj_InterfaceVersion(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x64a_Obj_InterfaceVersion(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);


int decode_can_0x64b_Obj_DistLong(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x64b_Obj_DistLong(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x64b_Obj_DistLat(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x64b_Obj_DistLat(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x64b_Obj_VrelLong(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x64b_Obj_VrelLong(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x64b_Obj_VrelLat(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x64b_Obj_VrelLat(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x64b_Obj_ID(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x64b_Obj_ID(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x64b_Obj_RCS(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x64b_Obj_RCS(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x64b_Obj_DynProp(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x64b_Obj_DynProp(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);


int decode_can_0x64c_Obj_ID(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x64c_Obj_ID(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x64c_Obj_DistLat_rms(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x64c_Obj_DistLat_rms(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x64c_Obj_DistLong_rms(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x64c_Obj_DistLong_rms(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x64c_Obj_VrelLat_rms(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x64c_Obj_VrelLat_rms(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x64c_Obj_VrelLong_rms(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x64c_Obj_VrelLong_rms(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x64c_Obj_ArelLong_rms(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x64c_Obj_ArelLong_rms(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x64c_Obj_Orientation_rms(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x64c_Obj_Orientation_rms(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x64c_Obj_ArelLat_rms(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x64c_Obj_ArelLat_rms(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x64c_Obj_MeasState(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x64c_Obj_MeasState(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x64c_Obj_ProbOfExist(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x64c_Obj_ProbOfExist(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);


int decode_can_0x64d_Obj_ArelLong(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x64d_Obj_ArelLong(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x64d_Obj_OrientationAngle(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x64d_Obj_OrientationAngle(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x64d_Obj_ArelLat(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x64d_Obj_ArelLat(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x64d_Obj_ID(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x64d_Obj_ID(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x64d_Obj_Length(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x64d_Obj_Length(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x64d_Obj_Width(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x64d_Obj_Width(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x64d_Obj_Class(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x64d_Obj_Class(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);


int decode_can_0x64e_Obj_ID(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x64e_Obj_ID(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x64e_Obj_CollDetRegionBitfield(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x64e_Obj_CollDetRegionBitfield(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);


int decode_can_0x740_Version_MajorRelease(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x740_Version_MajorRelease(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x740_Version_MinorRelease(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x740_Version_MinorRelease(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x740_Version_PatchLevel(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x740_Version_PatchLevel(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);


int decode_can_0x741_Cluster_DistLong(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x741_Cluster_DistLong(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x741_Cluster_DistLat(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x741_Cluster_DistLat(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x741_Cluster_VrelLong(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x741_Cluster_VrelLong(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x741_Cluster_VrelLat(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x741_Cluster_VrelLat(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x741_Cluster_ID(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x741_Cluster_ID(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x741_Cluster_RCS(const can_obj_ars408_can_database_ch4_h_t *o, double *out);
int encode_can_0x741_Cluster_RCS(can_obj_ars408_can_database_ch4_h_t *o, double in);
int decode_can_0x741_Cluster_DynProp(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x741_Cluster_DynProp(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);


int decode_can_0x742_Cluster_ID(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x742_Cluster_ID(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x742_Cluster_DistLat_rms(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x742_Cluster_DistLat_rms(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x742_Cluster_DistLong_rms(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x742_Cluster_DistLong_rms(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x742_Cluster_VrelLat_rms(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x742_Cluster_VrelLat_rms(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x742_Cluster_VrelLong_rms(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x742_Cluster_VrelLong_rms(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x742_Cluster_InvalidState(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x742_Cluster_InvalidState(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x742_Cluster_PdH0(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x742_Cluster_PdH0(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);
int decode_can_0x742_Cluster_AmbigState(const can_obj_ars408_can_database_ch4_h_t *o, uint8_t *out);
int encode_can_0x742_Cluster_AmbigState(can_obj_ars408_can_database_ch4_h_t *o, uint8_t in);


#ifdef __cplusplus
} 
#endif

#endif
