/* Generated by DBCC, see <https://github.com/howerj/dbcc> */
#include "ChangAn_CS55.h"
#include <inttypes.h>
#include <assert.h>

#define UNUSED(X) ((void)(X))

static inline uint64_t reverse_byte_order(uint64_t x) {
	x = (x & 0x00000000FFFFFFFF) << 32 | (x & 0xFFFFFFFF00000000) >> 32;
	x = (x & 0x0000FFFF0000FFFF) << 16 | (x & 0xFFFF0000FFFF0000) >> 16;
	x = (x & 0x00FF00FF00FF00FF) << 8  | (x & 0xFF00FF00FF00FF00) >> 8;
	return x;
}

static inline int print_helper(int r, int print_return_value) {
	return ((r >= 0) && (print_return_value >= 0)) ? r + print_return_value : -1;
}

static int pack_can_0x208_P_Can2_208(can_obj_changan_cs55_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* Wheel_Speed_RR_Data: start-bit 4, length 13, endianess motorola, scaling 0.05625, offset 0 */
	x = ((uint16_t)(o->can_0x208_P_Can2_208.Wheel_Speed_RR_Data)) & 0x1fff;
	x <<= 48; 
	m |= x;
	/* Wheel_Speed_RL_Data: start-bit 20, length 13, endianess motorola, scaling 0.05625, offset 0 */
	x = ((uint16_t)(o->can_0x208_P_Can2_208.Wheel_Speed_RL_Data)) & 0x1fff;
	x <<= 32; 
	m |= x;
	/* Wheel_Speed_FR_Data: start-bit 36, length 13, endianess motorola, scaling 0.05625, offset 0 */
	x = ((uint16_t)(o->can_0x208_P_Can2_208.Wheel_Speed_FR_Data)) & 0x1fff;
	x <<= 16; 
	m |= x;
	/* Wheel_Speed_FL_Data: start-bit 52, length 13, endianess motorola, scaling 0.05625, offset 0 */
	x = ((uint16_t)(o->can_0x208_P_Can2_208.Wheel_Speed_FL_Data)) & 0x1fff;
	m |= x;
	/* Wheel_Speed_RR_Direction: start-bit 6, length 2, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x208_P_Can2_208.Wheel_Speed_RR_Direction)) & 0x3;
	x <<= 61; 
	m |= x;
	/* Wheel_Speed_RL_Direction: start-bit 22, length 2, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x208_P_Can2_208.Wheel_Speed_RL_Direction)) & 0x3;
	x <<= 45; 
	m |= x;
	/* Wheel_Speed_FR_Direction: start-bit 38, length 2, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x208_P_Can2_208.Wheel_Speed_FR_Direction)) & 0x3;
	x <<= 29; 
	m |= x;
	/* Wheel_Speed_FL_Direction: start-bit 54, length 2, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x208_P_Can2_208.Wheel_Speed_FL_Direction)) & 0x3;
	x <<= 13; 
	m |= x;
	/* Wheel_Speed_RR_Valid_Data: start-bit 7, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x208_P_Can2_208.Wheel_Speed_RR_Valid_Data)) & 0x1;
	x <<= 63; 
	m |= x;
	/* Wheel_Speed_RL_Valid_Data: start-bit 23, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x208_P_Can2_208.Wheel_Speed_RL_Valid_Data)) & 0x1;
	x <<= 47; 
	m |= x;
	/* Wheel_Speed_FR_Valid_Data: start-bit 39, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x208_P_Can2_208.Wheel_Speed_FR_Valid_Data)) & 0x1;
	x <<= 31; 
	m |= x;
	/* Wheel_Speed_FL_Valid_Data: start-bit 55, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x208_P_Can2_208.Wheel_Speed_FL_Valid_Data)) & 0x1;
	x <<= 15; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x208_P_Can2_208_tx = 1;
	return 0;
}

static int unpack_can_0x208_P_Can2_208(can_obj_changan_cs55_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* Wheel_Speed_RR_Data: start-bit 4, length 13, endianess motorola, scaling 0.05625, offset 0 */
	x = (m >> 48) & 0x1fff;
	o->can_0x208_P_Can2_208.Wheel_Speed_RR_Data = x;
	/* Wheel_Speed_RL_Data: start-bit 20, length 13, endianess motorola, scaling 0.05625, offset 0 */
	x = (m >> 32) & 0x1fff;
	o->can_0x208_P_Can2_208.Wheel_Speed_RL_Data = x;
	/* Wheel_Speed_FR_Data: start-bit 36, length 13, endianess motorola, scaling 0.05625, offset 0 */
	x = (m >> 16) & 0x1fff;
	o->can_0x208_P_Can2_208.Wheel_Speed_FR_Data = x;
	/* Wheel_Speed_FL_Data: start-bit 52, length 13, endianess motorola, scaling 0.05625, offset 0 */
	x = m & 0x1fff;
	o->can_0x208_P_Can2_208.Wheel_Speed_FL_Data = x;
	/* Wheel_Speed_RR_Direction: start-bit 6, length 2, endianess motorola, scaling 1, offset 0 */
	x = (m >> 61) & 0x3;
	o->can_0x208_P_Can2_208.Wheel_Speed_RR_Direction = x;
	/* Wheel_Speed_RL_Direction: start-bit 22, length 2, endianess motorola, scaling 1, offset 0 */
	x = (m >> 45) & 0x3;
	o->can_0x208_P_Can2_208.Wheel_Speed_RL_Direction = x;
	/* Wheel_Speed_FR_Direction: start-bit 38, length 2, endianess motorola, scaling 1, offset 0 */
	x = (m >> 29) & 0x3;
	o->can_0x208_P_Can2_208.Wheel_Speed_FR_Direction = x;
	/* Wheel_Speed_FL_Direction: start-bit 54, length 2, endianess motorola, scaling 1, offset 0 */
	x = (m >> 13) & 0x3;
	o->can_0x208_P_Can2_208.Wheel_Speed_FL_Direction = x;
	/* Wheel_Speed_RR_Valid_Data: start-bit 7, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 63) & 0x1;
	o->can_0x208_P_Can2_208.Wheel_Speed_RR_Valid_Data = x;
	/* Wheel_Speed_RL_Valid_Data: start-bit 23, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 47) & 0x1;
	o->can_0x208_P_Can2_208.Wheel_Speed_RL_Valid_Data = x;
	/* Wheel_Speed_FR_Valid_Data: start-bit 39, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 31) & 0x1;
	o->can_0x208_P_Can2_208.Wheel_Speed_FR_Valid_Data = x;
	/* Wheel_Speed_FL_Valid_Data: start-bit 55, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 15) & 0x1;
	o->can_0x208_P_Can2_208.Wheel_Speed_FL_Valid_Data = x;
	o->can_0x208_P_Can2_208_rx = 1;
	o->can_0x208_P_Can2_208_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x208_Wheel_Speed_RR_Data(const can_obj_changan_cs55_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x208_P_Can2_208.Wheel_Speed_RR_Data);
	rval *= 0.05625;
	*out = rval;
	return 0;
}

int encode_can_0x208_Wheel_Speed_RR_Data(can_obj_changan_cs55_h_t *o, double in) {
	assert(o);
	in *= 17.7778;
	o->can_0x208_P_Can2_208.Wheel_Speed_RR_Data = in;
	return 0;
}

int decode_can_0x208_Wheel_Speed_RL_Data(const can_obj_changan_cs55_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x208_P_Can2_208.Wheel_Speed_RL_Data);
	rval *= 0.05625;
	*out = rval;
	return 0;
}

int encode_can_0x208_Wheel_Speed_RL_Data(can_obj_changan_cs55_h_t *o, double in) {
	assert(o);
	in *= 17.7778;
	o->can_0x208_P_Can2_208.Wheel_Speed_RL_Data = in;
	return 0;
}

int decode_can_0x208_Wheel_Speed_FR_Data(const can_obj_changan_cs55_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x208_P_Can2_208.Wheel_Speed_FR_Data);
	rval *= 0.05625;
	*out = rval;
	return 0;
}

int encode_can_0x208_Wheel_Speed_FR_Data(can_obj_changan_cs55_h_t *o, double in) {
	assert(o);
	in *= 17.7778;
	o->can_0x208_P_Can2_208.Wheel_Speed_FR_Data = in;
	return 0;
}

int decode_can_0x208_Wheel_Speed_FL_Data(const can_obj_changan_cs55_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x208_P_Can2_208.Wheel_Speed_FL_Data);
	rval *= 0.05625;
	*out = rval;
	return 0;
}

int encode_can_0x208_Wheel_Speed_FL_Data(can_obj_changan_cs55_h_t *o, double in) {
	assert(o);
	in *= 17.7778;
	o->can_0x208_P_Can2_208.Wheel_Speed_FL_Data = in;
	return 0;
}

int decode_can_0x208_Wheel_Speed_RR_Direction(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x208_P_Can2_208.Wheel_Speed_RR_Direction);
	*out = rval;
	return 0;
}

int encode_can_0x208_Wheel_Speed_RR_Direction(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x208_P_Can2_208.Wheel_Speed_RR_Direction = in;
	return 0;
}

int decode_can_0x208_Wheel_Speed_RL_Direction(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x208_P_Can2_208.Wheel_Speed_RL_Direction);
	*out = rval;
	return 0;
}

int encode_can_0x208_Wheel_Speed_RL_Direction(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x208_P_Can2_208.Wheel_Speed_RL_Direction = in;
	return 0;
}

int decode_can_0x208_Wheel_Speed_FR_Direction(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x208_P_Can2_208.Wheel_Speed_FR_Direction);
	*out = rval;
	return 0;
}

int encode_can_0x208_Wheel_Speed_FR_Direction(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x208_P_Can2_208.Wheel_Speed_FR_Direction = in;
	return 0;
}

int decode_can_0x208_Wheel_Speed_FL_Direction(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x208_P_Can2_208.Wheel_Speed_FL_Direction);
	*out = rval;
	return 0;
}

int encode_can_0x208_Wheel_Speed_FL_Direction(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x208_P_Can2_208.Wheel_Speed_FL_Direction = in;
	return 0;
}

int decode_can_0x208_Wheel_Speed_RR_Valid_Data(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x208_P_Can2_208.Wheel_Speed_RR_Valid_Data);
	*out = rval;
	return 0;
}

int encode_can_0x208_Wheel_Speed_RR_Valid_Data(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x208_P_Can2_208.Wheel_Speed_RR_Valid_Data = in;
	return 0;
}

int decode_can_0x208_Wheel_Speed_RL_Valid_Data(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x208_P_Can2_208.Wheel_Speed_RL_Valid_Data);
	*out = rval;
	return 0;
}

int encode_can_0x208_Wheel_Speed_RL_Valid_Data(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x208_P_Can2_208.Wheel_Speed_RL_Valid_Data = in;
	return 0;
}

int decode_can_0x208_Wheel_Speed_FR_Valid_Data(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x208_P_Can2_208.Wheel_Speed_FR_Valid_Data);
	*out = rval;
	return 0;
}

int encode_can_0x208_Wheel_Speed_FR_Valid_Data(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x208_P_Can2_208.Wheel_Speed_FR_Valid_Data = in;
	return 0;
}

int decode_can_0x208_Wheel_Speed_FL_Valid_Data(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x208_P_Can2_208.Wheel_Speed_FL_Valid_Data);
	*out = rval;
	return 0;
}

int encode_can_0x208_Wheel_Speed_FL_Valid_Data(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x208_P_Can2_208.Wheel_Speed_FL_Valid_Data = in;
	return 0;
}

int print_can_0x208_P_Can2_208(const can_obj_changan_cs55_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, printf("Wheel_Speed_RR_Data = (wire: %.0f)\n", (double)(o->can_0x208_P_Can2_208.Wheel_Speed_RR_Data)));
	r = print_helper(r, printf("Wheel_Speed_RL_Data = (wire: %.0f)\n", (double)(o->can_0x208_P_Can2_208.Wheel_Speed_RL_Data)));
	r = print_helper(r, printf("Wheel_Speed_FR_Data = (wire: %.0f)\n", (double)(o->can_0x208_P_Can2_208.Wheel_Speed_FR_Data)));
	r = print_helper(r, printf("Wheel_Speed_FL_Data = (wire: %.0f)\n", (double)(o->can_0x208_P_Can2_208.Wheel_Speed_FL_Data)));
	r = print_helper(r, printf("Wheel_Speed_RR_Direction = (wire: %.0f)\n", (double)(o->can_0x208_P_Can2_208.Wheel_Speed_RR_Direction)));
	r = print_helper(r, printf("Wheel_Speed_RL_Direction = (wire: %.0f)\n", (double)(o->can_0x208_P_Can2_208.Wheel_Speed_RL_Direction)));
	r = print_helper(r, printf("Wheel_Speed_FR_Direction = (wire: %.0f)\n", (double)(o->can_0x208_P_Can2_208.Wheel_Speed_FR_Direction)));
	r = print_helper(r, printf("Wheel_Speed_FL_Direction = (wire: %.0f)\n", (double)(o->can_0x208_P_Can2_208.Wheel_Speed_FL_Direction)));
	r = print_helper(r, printf("Wheel_Speed_RR_Valid_Data = (wire: %.0f)\n", (double)(o->can_0x208_P_Can2_208.Wheel_Speed_RR_Valid_Data)));
	r = print_helper(r, printf("Wheel_Speed_RL_Valid_Data = (wire: %.0f)\n", (double)(o->can_0x208_P_Can2_208.Wheel_Speed_RL_Valid_Data)));
	r = print_helper(r, printf("Wheel_Speed_FR_Valid_Data = (wire: %.0f)\n", (double)(o->can_0x208_P_Can2_208.Wheel_Speed_FR_Valid_Data)));
	r = print_helper(r, printf("Wheel_Speed_FL_Valid_Data = (wire: %.0f)\n", (double)(o->can_0x208_P_Can2_208.Wheel_Speed_FL_Valid_Data)));
	return r;
}

static int pack_can_0x218_EPBi_218(can_obj_changan_cs55_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* ESP_VehicleSpeed: start-bit 36, length 13, endianess motorola, scaling 0.05625, offset 0 */
	x = ((uint16_t)(o->can_0x218_EPBi_218.ESP_VehicleSpeed)) & 0x1fff;
	x <<= 16; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x218_EPBi_218_tx = 1;
	return 0;
}

static int unpack_can_0x218_EPBi_218(can_obj_changan_cs55_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 6)
		return -1;
	/* ESP_VehicleSpeed: start-bit 36, length 13, endianess motorola, scaling 0.05625, offset 0 */
	x = (m >> 16) & 0x1fff;
	o->can_0x218_EPBi_218.ESP_VehicleSpeed = x;
	o->can_0x218_EPBi_218_rx = 1;
	o->can_0x218_EPBi_218_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x218_ESP_VehicleSpeed(const can_obj_changan_cs55_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x218_EPBi_218.ESP_VehicleSpeed);
	rval *= 0.05625;
	if (rval <= 360) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x218_ESP_VehicleSpeed(can_obj_changan_cs55_h_t *o, double in) {
	assert(o);
	o->can_0x218_EPBi_218.ESP_VehicleSpeed = 0;
	if (in > 360)
		return -1;
	in *= 17.7778;
	o->can_0x218_EPBi_218.ESP_VehicleSpeed = in;
	return 0;
}

int print_can_0x218_EPBi_218(const can_obj_changan_cs55_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, printf("ESP_VehicleSpeed = (wire: %.0f)\n", (double)(o->can_0x218_EPBi_218.ESP_VehicleSpeed)));
	return r;
}

static int pack_can_0x24e_ACC_24E(can_obj_changan_cs55_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* ACC_ACCTargetAcceleration: start-bit 7, length 8, endianess motorola, scaling 0.05, offset -5 */
	x = ((uint8_t)(o->can_0x24e_ACC_24E.ACC_ACCTargetAcceleration)) & 0xff;
	x <<= 56; 
	m |= x;
	/* ACC_CheckSum_id24E: start-bit 63, length 8, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x24e_ACC_24E.ACC_CheckSum_id24E)) & 0xff;
	m |= x;
	/* ACC_RollingCounter_id24E: start-bit 51, length 4, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x24e_ACC_24E.ACC_RollingCounter_id24E)) & 0xf;
	x <<= 8; 
	m |= x;
	/* ACC_DecToStop: start-bit 31, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x24e_ACC_24E.ACC_DecToStop)) & 0x1;
	x <<= 39; 
	m |= x;
	/* ACC_CDDAxEna: start-bit 44, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x24e_ACC_24E.ACC_CDDAxEna)) & 0x1;
	x <<= 20; 
	m |= x;
	/* ACC_Driveoff_Request: start-bit 55, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x24e_ACC_24E.ACC_Driveoff_Request)) & 0x1;
	x <<= 15; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x24e_ACC_24E_tx = 1;
	return 0;
}

static int unpack_can_0x24e_ACC_24E(can_obj_changan_cs55_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* ACC_ACCTargetAcceleration: start-bit 7, length 8, endianess motorola, scaling 0.05, offset -5 */
	x = (m >> 56) & 0xff;
	o->can_0x24e_ACC_24E.ACC_ACCTargetAcceleration = x;
	/* ACC_CheckSum_id24E: start-bit 63, length 8, endianess motorola, scaling 1, offset 0 */
	x = m & 0xff;
	o->can_0x24e_ACC_24E.ACC_CheckSum_id24E = x;
	/* ACC_RollingCounter_id24E: start-bit 51, length 4, endianess motorola, scaling 1, offset 0 */
	x = (m >> 8) & 0xf;
	o->can_0x24e_ACC_24E.ACC_RollingCounter_id24E = x;
	/* ACC_DecToStop: start-bit 31, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 39) & 0x1;
	o->can_0x24e_ACC_24E.ACC_DecToStop = x;
	/* ACC_CDDAxEna: start-bit 44, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 20) & 0x1;
	o->can_0x24e_ACC_24E.ACC_CDDAxEna = x;
	/* ACC_Driveoff_Request: start-bit 55, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 15) & 0x1;
	o->can_0x24e_ACC_24E.ACC_Driveoff_Request = x;
	o->can_0x24e_ACC_24E_rx = 1;
	o->can_0x24e_ACC_24E_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x24e_ACC_ACCTargetAcceleration(const can_obj_changan_cs55_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x24e_ACC_24E.ACC_ACCTargetAcceleration);
	rval *= 0.05;
	rval += -5;
	if (rval <= 7.75) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x24e_ACC_ACCTargetAcceleration(can_obj_changan_cs55_h_t *o, double in) {
	assert(o);
	o->can_0x24e_ACC_24E.ACC_ACCTargetAcceleration = 0;
	if (in > 7.75)
		return -1;
	in += 5;
	in *= 20;
	o->can_0x24e_ACC_24E.ACC_ACCTargetAcceleration = in;
	return 0;
}

int decode_can_0x24e_ACC_CheckSum_id24E(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x24e_ACC_24E.ACC_CheckSum_id24E);
	*out = rval;
	return 0;
}

int encode_can_0x24e_ACC_CheckSum_id24E(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x24e_ACC_24E.ACC_CheckSum_id24E = in;
	return 0;
}

int decode_can_0x24e_ACC_RollingCounter_id24E(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x24e_ACC_24E.ACC_RollingCounter_id24E);
	*out = rval;
	return 0;
}

int encode_can_0x24e_ACC_RollingCounter_id24E(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x24e_ACC_24E.ACC_RollingCounter_id24E = in;
	return 0;
}

int decode_can_0x24e_ACC_DecToStop(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x24e_ACC_24E.ACC_DecToStop);
	*out = rval;
	return 0;
}

int encode_can_0x24e_ACC_DecToStop(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x24e_ACC_24E.ACC_DecToStop = in;
	return 0;
}

int decode_can_0x24e_ACC_CDDAxEna(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x24e_ACC_24E.ACC_CDDAxEna);
	*out = rval;
	return 0;
}

int encode_can_0x24e_ACC_CDDAxEna(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x24e_ACC_24E.ACC_CDDAxEna = in;
	return 0;
}

int decode_can_0x24e_ACC_Driveoff_Request(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x24e_ACC_24E.ACC_Driveoff_Request);
	*out = rval;
	return 0;
}

int encode_can_0x24e_ACC_Driveoff_Request(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x24e_ACC_24E.ACC_Driveoff_Request = in;
	return 0;
}

int print_can_0x24e_ACC_24E(const can_obj_changan_cs55_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, printf("ACC_ACCTargetAcceleration = (wire: %.0f)\n", (double)(o->can_0x24e_ACC_24E.ACC_ACCTargetAcceleration)));
	r = print_helper(r, printf("ACC_CheckSum_id24E = (wire: %.0f)\n", (double)(o->can_0x24e_ACC_24E.ACC_CheckSum_id24E)));
	r = print_helper(r, printf("ACC_RollingCounter_id24E = (wire: %.0f)\n", (double)(o->can_0x24e_ACC_24E.ACC_RollingCounter_id24E)));
	r = print_helper(r, printf("ACC_DecToStop = (wire: %.0f)\n", (double)(o->can_0x24e_ACC_24E.ACC_DecToStop)));
	r = print_helper(r, printf("ACC_CDDAxEna = (wire: %.0f)\n", (double)(o->can_0x24e_ACC_24E.ACC_CDDAxEna)));
	r = print_helper(r, printf("ACC_Driveoff_Request = (wire: %.0f)\n", (double)(o->can_0x24e_ACC_24E.ACC_Driveoff_Request)));
	return r;
}

static int pack_can_0x255_EMS_255(can_obj_changan_cs55_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* EMS_QECACC: start-bit 7, length 2, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x255_EMS_255.EMS_QECACC)) & 0x3;
	x <<= 62; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x255_EMS_255_tx = 1;
	return 0;
}

static int unpack_can_0x255_EMS_255(can_obj_changan_cs55_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* EMS_QECACC: start-bit 7, length 2, endianess motorola, scaling 1, offset 0 */
	x = (m >> 62) & 0x3;
	o->can_0x255_EMS_255.EMS_QECACC = x;
	o->can_0x255_EMS_255_rx = 1;
	o->can_0x255_EMS_255_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x255_EMS_QECACC(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x255_EMS_255.EMS_QECACC);
	*out = rval;
	return 0;
}

int encode_can_0x255_EMS_QECACC(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x255_EMS_255.EMS_QECACC = in;
	return 0;
}

int print_can_0x255_EMS_255(const can_obj_changan_cs55_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, printf("EMS_QECACC = (wire: %.0f)\n", (double)(o->can_0x255_EMS_255.EMS_QECACC)));
	return r;
}

static int pack_can_0x258_P_Can1_258(can_obj_changan_cs55_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* Wheel_Speed_RR_Pulse: start-bit 39, length 8, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x258_P_Can1_258.Wheel_Speed_RR_Pulse)) & 0xff;
	x <<= 24; 
	m |= x;
	/* Wheel_Speed_RL_Pulse: start-bit 47, length 8, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x258_P_Can1_258.Wheel_Speed_RL_Pulse)) & 0xff;
	x <<= 16; 
	m |= x;
	/* Wheel_Speed_FR_Pulse: start-bit 55, length 8, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x258_P_Can1_258.Wheel_Speed_FR_Pulse)) & 0xff;
	x <<= 8; 
	m |= x;
	/* Wheel_Speed_FL_Pulse: start-bit 63, length 8, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x258_P_Can1_258.Wheel_Speed_FL_Pulse)) & 0xff;
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x258_P_Can1_258_tx = 1;
	return 0;
}

static int unpack_can_0x258_P_Can1_258(can_obj_changan_cs55_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* Wheel_Speed_RR_Pulse: start-bit 39, length 8, endianess motorola, scaling 1, offset 0 */
	x = (m >> 24) & 0xff;
	o->can_0x258_P_Can1_258.Wheel_Speed_RR_Pulse = x;
	/* Wheel_Speed_RL_Pulse: start-bit 47, length 8, endianess motorola, scaling 1, offset 0 */
	x = (m >> 16) & 0xff;
	o->can_0x258_P_Can1_258.Wheel_Speed_RL_Pulse = x;
	/* Wheel_Speed_FR_Pulse: start-bit 55, length 8, endianess motorola, scaling 1, offset 0 */
	x = (m >> 8) & 0xff;
	o->can_0x258_P_Can1_258.Wheel_Speed_FR_Pulse = x;
	/* Wheel_Speed_FL_Pulse: start-bit 63, length 8, endianess motorola, scaling 1, offset 0 */
	x = m & 0xff;
	o->can_0x258_P_Can1_258.Wheel_Speed_FL_Pulse = x;
	o->can_0x258_P_Can1_258_rx = 1;
	o->can_0x258_P_Can1_258_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x258_Wheel_Speed_RR_Pulse(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x258_P_Can1_258.Wheel_Speed_RR_Pulse);
	*out = rval;
	return 0;
}

int encode_can_0x258_Wheel_Speed_RR_Pulse(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x258_P_Can1_258.Wheel_Speed_RR_Pulse = in;
	return 0;
}

int decode_can_0x258_Wheel_Speed_RL_Pulse(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x258_P_Can1_258.Wheel_Speed_RL_Pulse);
	*out = rval;
	return 0;
}

int encode_can_0x258_Wheel_Speed_RL_Pulse(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x258_P_Can1_258.Wheel_Speed_RL_Pulse = in;
	return 0;
}

int decode_can_0x258_Wheel_Speed_FR_Pulse(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x258_P_Can1_258.Wheel_Speed_FR_Pulse);
	*out = rval;
	return 0;
}

int encode_can_0x258_Wheel_Speed_FR_Pulse(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x258_P_Can1_258.Wheel_Speed_FR_Pulse = in;
	return 0;
}

int decode_can_0x258_Wheel_Speed_FL_Pulse(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x258_P_Can1_258.Wheel_Speed_FL_Pulse);
	*out = rval;
	return 0;
}

int encode_can_0x258_Wheel_Speed_FL_Pulse(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x258_P_Can1_258.Wheel_Speed_FL_Pulse = in;
	return 0;
}

int print_can_0x258_P_Can1_258(const can_obj_changan_cs55_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, printf("Wheel_Speed_RR_Pulse = (wire: %.0f)\n", (double)(o->can_0x258_P_Can1_258.Wheel_Speed_RR_Pulse)));
	r = print_helper(r, printf("Wheel_Speed_RL_Pulse = (wire: %.0f)\n", (double)(o->can_0x258_P_Can1_258.Wheel_Speed_RL_Pulse)));
	r = print_helper(r, printf("Wheel_Speed_FR_Pulse = (wire: %.0f)\n", (double)(o->can_0x258_P_Can1_258.Wheel_Speed_FR_Pulse)));
	r = print_helper(r, printf("Wheel_Speed_FL_Pulse = (wire: %.0f)\n", (double)(o->can_0x258_P_Can1_258.Wheel_Speed_FL_Pulse)));
	return r;
}

static int pack_can_0x25e_ACC_25E(can_obj_changan_cs55_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* ACC_AEBTargetDeceleration: start-bit 7, length 16, endianess motorola, scaling 0.0005, offset -16 */
	x = ((uint16_t)(o->can_0x25e_ACC_25E.ACC_AEBTargetDeceleration)) & 0xffff;
	x <<= 48; 
	m |= x;
	/* ACC_ACCTrqReq: start-bit 36, length 10, endianess motorola, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x25e_ACC_25E.ACC_ACCTrqReq)) & 0x3ff;
	x <<= 19; 
	m |= x;
	/* ACC_CheckSum_id25E: start-bit 63, length 8, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x25e_ACC_25E.ACC_CheckSum_id25E)) & 0xff;
	m |= x;
	/* ACC_RollingCounter_id25E: start-bit 51, length 4, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x25e_ACC_25E.ACC_RollingCounter_id25E)) & 0xf;
	x <<= 8; 
	m |= x;
	/* ACC_AEBDecCtrlAvail: start-bit 23, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x25e_ACC_25E.ACC_AEBDecCtrlAvail)) & 0x1;
	x <<= 47; 
	m |= x;
	/* ACC_ACCTrqReqEna: start-bit 42, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x25e_ACC_25E.ACC_ACCTrqReqEna)) & 0x1;
	x <<= 18; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x25e_ACC_25E_tx = 1;
	return 0;
}

static int unpack_can_0x25e_ACC_25E(can_obj_changan_cs55_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* ACC_AEBTargetDeceleration: start-bit 7, length 16, endianess motorola, scaling 0.0005, offset -16 */
	x = (m >> 48) & 0xffff;
	o->can_0x25e_ACC_25E.ACC_AEBTargetDeceleration = x;
	/* ACC_ACCTrqReq: start-bit 36, length 10, endianess motorola, scaling 1, offset 0 */
	x = (m >> 19) & 0x3ff;
	o->can_0x25e_ACC_25E.ACC_ACCTrqReq = x;
	/* ACC_CheckSum_id25E: start-bit 63, length 8, endianess motorola, scaling 1, offset 0 */
	x = m & 0xff;
	o->can_0x25e_ACC_25E.ACC_CheckSum_id25E = x;
	/* ACC_RollingCounter_id25E: start-bit 51, length 4, endianess motorola, scaling 1, offset 0 */
	x = (m >> 8) & 0xf;
	o->can_0x25e_ACC_25E.ACC_RollingCounter_id25E = x;
	/* ACC_AEBDecCtrlAvail: start-bit 23, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 47) & 0x1;
	o->can_0x25e_ACC_25E.ACC_AEBDecCtrlAvail = x;
	/* ACC_ACCTrqReqEna: start-bit 42, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 18) & 0x1;
	o->can_0x25e_ACC_25E.ACC_ACCTrqReqEna = x;
	o->can_0x25e_ACC_25E_rx = 1;
	o->can_0x25e_ACC_25E_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x25e_ACC_AEBTargetDeceleration(const can_obj_changan_cs55_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x25e_ACC_25E.ACC_AEBTargetDeceleration);
	rval *= 0.0005;
	rval += -16;
	if (rval <= 16) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x25e_ACC_AEBTargetDeceleration(can_obj_changan_cs55_h_t *o, double in) {
	assert(o);
	o->can_0x25e_ACC_25E.ACC_AEBTargetDeceleration = 0;
	if (in > 16)
		return -1;
	in += 16;
	in *= 2000;
	o->can_0x25e_ACC_25E.ACC_AEBTargetDeceleration = in;
	return 0;
}

int decode_can_0x25e_ACC_ACCTrqReq(const can_obj_changan_cs55_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x25e_ACC_25E.ACC_ACCTrqReq);
	*out = rval;
	return 0;
}

int encode_can_0x25e_ACC_ACCTrqReq(can_obj_changan_cs55_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x25e_ACC_25E.ACC_ACCTrqReq = in;
	return 0;
}

int decode_can_0x25e_ACC_CheckSum_id25E(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x25e_ACC_25E.ACC_CheckSum_id25E);
	*out = rval;
	return 0;
}

int encode_can_0x25e_ACC_CheckSum_id25E(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x25e_ACC_25E.ACC_CheckSum_id25E = in;
	return 0;
}

int decode_can_0x25e_ACC_RollingCounter_id25E(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x25e_ACC_25E.ACC_RollingCounter_id25E);
	*out = rval;
	return 0;
}

int encode_can_0x25e_ACC_RollingCounter_id25E(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x25e_ACC_25E.ACC_RollingCounter_id25E = in;
	return 0;
}

int decode_can_0x25e_ACC_AEBDecCtrlAvail(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x25e_ACC_25E.ACC_AEBDecCtrlAvail);
	*out = rval;
	return 0;
}

int encode_can_0x25e_ACC_AEBDecCtrlAvail(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x25e_ACC_25E.ACC_AEBDecCtrlAvail = in;
	return 0;
}

int decode_can_0x25e_ACC_ACCTrqReqEna(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x25e_ACC_25E.ACC_ACCTrqReqEna);
	*out = rval;
	return 0;
}

int encode_can_0x25e_ACC_ACCTrqReqEna(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x25e_ACC_25E.ACC_ACCTrqReqEna = in;
	return 0;
}

int print_can_0x25e_ACC_25E(const can_obj_changan_cs55_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, printf("ACC_AEBTargetDeceleration = (wire: %.0f)\n", (double)(o->can_0x25e_ACC_25E.ACC_AEBTargetDeceleration)));
	r = print_helper(r, printf("ACC_ACCTrqReq = (wire: %.0f)\n", (double)(o->can_0x25e_ACC_25E.ACC_ACCTrqReq)));
	r = print_helper(r, printf("ACC_CheckSum_id25E = (wire: %.0f)\n", (double)(o->can_0x25e_ACC_25E.ACC_CheckSum_id25E)));
	r = print_helper(r, printf("ACC_RollingCounter_id25E = (wire: %.0f)\n", (double)(o->can_0x25e_ACC_25E.ACC_RollingCounter_id25E)));
	r = print_helper(r, printf("ACC_AEBDecCtrlAvail = (wire: %.0f)\n", (double)(o->can_0x25e_ACC_25E.ACC_AEBDecCtrlAvail)));
	r = print_helper(r, printf("ACC_ACCTrqReqEna = (wire: %.0f)\n", (double)(o->can_0x25e_ACC_25E.ACC_ACCTrqReqEna)));
	return r;
}

static int pack_can_0x278_EPBi_278(can_obj_changan_cs55_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* ESP_YawRate: start-bit 37, length 14, endianess motorola, scaling 0.01, offset -81.91 */
	x = ((uint16_t)(o->can_0x278_EPBi_278.ESP_YawRate)) & 0x3fff;
	x <<= 16; 
	m |= x;
	/* ESP_YawRate_Valid: start-bit 55, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x278_EPBi_278.ESP_YawRate_Valid)) & 0x1;
	x <<= 15; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x278_EPBi_278_tx = 1;
	return 0;
}

static int unpack_can_0x278_EPBi_278(can_obj_changan_cs55_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* ESP_YawRate: start-bit 37, length 14, endianess motorola, scaling 0.01, offset -81.91 */
	x = (m >> 16) & 0x3fff;
	o->can_0x278_EPBi_278.ESP_YawRate = x;
	/* ESP_YawRate_Valid: start-bit 55, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 15) & 0x1;
	o->can_0x278_EPBi_278.ESP_YawRate_Valid = x;
	o->can_0x278_EPBi_278_rx = 1;
	o->can_0x278_EPBi_278_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x278_ESP_YawRate(const can_obj_changan_cs55_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x278_EPBi_278.ESP_YawRate);
	rval *= 0.01;
	rval += -81.91;
	if (rval <= 81.91) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x278_ESP_YawRate(can_obj_changan_cs55_h_t *o, double in) {
	assert(o);
	o->can_0x278_EPBi_278.ESP_YawRate = 0;
	if (in > 81.91)
		return -1;
	in += 81.91;
	in *= 100;
	o->can_0x278_EPBi_278.ESP_YawRate = in;
	return 0;
}

int decode_can_0x278_ESP_YawRate_Valid(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x278_EPBi_278.ESP_YawRate_Valid);
	*out = rval;
	return 0;
}

int encode_can_0x278_ESP_YawRate_Valid(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x278_EPBi_278.ESP_YawRate_Valid = in;
	return 0;
}

int print_can_0x278_EPBi_278(const can_obj_changan_cs55_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, printf("ESP_YawRate = (wire: %.0f)\n", (double)(o->can_0x278_EPBi_278.ESP_YawRate)));
	r = print_helper(r, printf("ESP_YawRate_Valid = (wire: %.0f)\n", (double)(o->can_0x278_EPBi_278.ESP_YawRate_Valid)));
	return r;
}

static int pack_can_0x2a0_EPS_2A0(can_obj_changan_cs55_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* EPS_APA_EpasFAILED: start-bit 9, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x2a0_EPS_2A0.EPS_APA_EpasFAILED)) & 0x1;
	x <<= 49; 
	m |= x;
	/* EPS_APA_ControlFeedback: start-bit 29, length 1, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x2a0_EPS_2A0.EPS_APA_ControlFeedback)) & 0x1;
	x <<= 37; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x2a0_EPS_2A0_tx = 1;
	return 0;
}

static int unpack_can_0x2a0_EPS_2A0(can_obj_changan_cs55_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* EPS_APA_EpasFAILED: start-bit 9, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 49) & 0x1;
	o->can_0x2a0_EPS_2A0.EPS_APA_EpasFAILED = x;
	/* EPS_APA_ControlFeedback: start-bit 29, length 1, endianess motorola, scaling 1, offset 0 */
	x = (m >> 37) & 0x1;
	o->can_0x2a0_EPS_2A0.EPS_APA_ControlFeedback = x;
	o->can_0x2a0_EPS_2A0_rx = 1;
	o->can_0x2a0_EPS_2A0_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x2a0_EPS_APA_EpasFAILED(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x2a0_EPS_2A0.EPS_APA_EpasFAILED);
	*out = rval;
	return 0;
}

int encode_can_0x2a0_EPS_APA_EpasFAILED(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x2a0_EPS_2A0.EPS_APA_EpasFAILED = in;
	return 0;
}

int decode_can_0x2a0_EPS_APA_ControlFeedback(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x2a0_EPS_2A0.EPS_APA_ControlFeedback);
	*out = rval;
	return 0;
}

int encode_can_0x2a0_EPS_APA_ControlFeedback(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x2a0_EPS_2A0.EPS_APA_ControlFeedback = in;
	return 0;
}

int print_can_0x2a0_EPS_2A0(const can_obj_changan_cs55_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, printf("EPS_APA_EpasFAILED = (wire: %.0f)\n", (double)(o->can_0x2a0_EPS_2A0.EPS_APA_EpasFAILED)));
	r = print_helper(r, printf("EPS_APA_ControlFeedback = (wire: %.0f)\n", (double)(o->can_0x2a0_EPS_2A0.EPS_APA_ControlFeedback)));
	return r;
}

static int pack_can_0x2a1_EPS_2A1(can_obj_changan_cs55_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* EPS_SteeringAngle: start-bit 5, length 14, endianess motorola, scaling 0.15, offset -1228.65 */
	x = ((uint16_t)(o->can_0x2a1_EPS_2A1.EPS_SteeringAngle)) & 0x3fff;
	x <<= 48; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x2a1_EPS_2A1_tx = 1;
	return 0;
}

static int unpack_can_0x2a1_EPS_2A1(can_obj_changan_cs55_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* EPS_SteeringAngle: start-bit 5, length 14, endianess motorola, scaling 0.15, offset -1228.65 */
	x = (m >> 48) & 0x3fff;
	o->can_0x2a1_EPS_2A1.EPS_SteeringAngle = x;
	o->can_0x2a1_EPS_2A1_rx = 1;
	o->can_0x2a1_EPS_2A1_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x2a1_EPS_SteeringAngle(const can_obj_changan_cs55_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x2a1_EPS_2A1.EPS_SteeringAngle);
	rval *= 0.15;
	rval += -1228.65;
	if (rval <= 1228.65) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x2a1_EPS_SteeringAngle(can_obj_changan_cs55_h_t *o, double in) {
	assert(o);
	o->can_0x2a1_EPS_2A1.EPS_SteeringAngle = 0;
	if (in > 1228.65)
		return -1;
	in += 1228.65;
	in *= 6.66667;
	o->can_0x2a1_EPS_2A1.EPS_SteeringAngle = in;
	return 0;
}

int print_can_0x2a1_EPS_2A1(const can_obj_changan_cs55_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, printf("EPS_SteeringAngle = (wire: %.0f)\n", (double)(o->can_0x2a1_EPS_2A1.EPS_SteeringAngle)));
	return r;
}

static int pack_can_0x2a8_APA_ParkNoticeInfo_2A8(can_obj_changan_cs55_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* APA_SteeringAngleReq: start-bit 15, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x2a8_APA_ParkNoticeInfo_2A8.APA_SteeringAngleReq)) & 0xffff;
	x <<= 40; 
	m |= x;
	/* APA_CheckSum: start-bit 63, length 8, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x2a8_APA_ParkNoticeInfo_2A8.APA_CheckSum)) & 0xff;
	m |= x;
	/* APA_RollingCounter: start-bit 51, length 4, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x2a8_APA_ParkNoticeInfo_2A8.APA_RollingCounter)) & 0xf;
	x <<= 8; 
	m |= x;
	/* APA_StrAngReqType: start-bit 1, length 2, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x2a8_APA_ParkNoticeInfo_2A8.APA_StrAngReqType)) & 0x3;
	x <<= 56; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x2a8_APA_ParkNoticeInfo_2A8_tx = 1;
	return 0;
}

static int unpack_can_0x2a8_APA_ParkNoticeInfo_2A8(can_obj_changan_cs55_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* APA_SteeringAngleReq: start-bit 15, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 40) & 0xffff;
	o->can_0x2a8_APA_ParkNoticeInfo_2A8.APA_SteeringAngleReq = x;
	/* APA_CheckSum: start-bit 63, length 8, endianess motorola, scaling 1, offset 0 */
	x = m & 0xff;
	o->can_0x2a8_APA_ParkNoticeInfo_2A8.APA_CheckSum = x;
	/* APA_RollingCounter: start-bit 51, length 4, endianess motorola, scaling 1, offset 0 */
	x = (m >> 8) & 0xf;
	o->can_0x2a8_APA_ParkNoticeInfo_2A8.APA_RollingCounter = x;
	/* APA_StrAngReqType: start-bit 1, length 2, endianess motorola, scaling 1, offset 0 */
	x = (m >> 56) & 0x3;
	o->can_0x2a8_APA_ParkNoticeInfo_2A8.APA_StrAngReqType = x;
	o->can_0x2a8_APA_ParkNoticeInfo_2A8_rx = 1;
	o->can_0x2a8_APA_ParkNoticeInfo_2A8_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x2a8_APA_SteeringAngleReq(const can_obj_changan_cs55_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x2a8_APA_ParkNoticeInfo_2A8.APA_SteeringAngleReq);
	rval *= 0.1;
	if ((rval >= -780) && (rval <= 780)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x2a8_APA_SteeringAngleReq(can_obj_changan_cs55_h_t *o, double in) {
	assert(o);
	o->can_0x2a8_APA_ParkNoticeInfo_2A8.APA_SteeringAngleReq = 0;
	if (in < -780)
		return -1;
	if (in > 780)
		return -1;
	in *= 10;
	o->can_0x2a8_APA_ParkNoticeInfo_2A8.APA_SteeringAngleReq = in;
	return 0;
}

int decode_can_0x2a8_APA_CheckSum(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x2a8_APA_ParkNoticeInfo_2A8.APA_CheckSum);
	*out = rval;
	return 0;
}

int encode_can_0x2a8_APA_CheckSum(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x2a8_APA_ParkNoticeInfo_2A8.APA_CheckSum = in;
	return 0;
}

int decode_can_0x2a8_APA_RollingCounter(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x2a8_APA_ParkNoticeInfo_2A8.APA_RollingCounter);
	*out = rval;
	return 0;
}

int encode_can_0x2a8_APA_RollingCounter(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x2a8_APA_ParkNoticeInfo_2A8.APA_RollingCounter = in;
	return 0;
}

int decode_can_0x2a8_APA_StrAngReqType(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x2a8_APA_ParkNoticeInfo_2A8.APA_StrAngReqType);
	*out = rval;
	return 0;
}

int encode_can_0x2a8_APA_StrAngReqType(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x2a8_APA_ParkNoticeInfo_2A8.APA_StrAngReqType = in;
	return 0;
}

int print_can_0x2a8_APA_ParkNoticeInfo_2A8(const can_obj_changan_cs55_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, printf("APA_SteeringAngleReq = (wire: %.0f)\n", (double)(o->can_0x2a8_APA_ParkNoticeInfo_2A8.APA_SteeringAngleReq)));
	r = print_helper(r, printf("APA_CheckSum = (wire: %.0f)\n", (double)(o->can_0x2a8_APA_ParkNoticeInfo_2A8.APA_CheckSum)));
	r = print_helper(r, printf("APA_RollingCounter = (wire: %.0f)\n", (double)(o->can_0x2a8_APA_ParkNoticeInfo_2A8.APA_RollingCounter)));
	r = print_helper(r, printf("APA_StrAngReqType = (wire: %.0f)\n", (double)(o->can_0x2a8_APA_ParkNoticeInfo_2A8.APA_StrAngReqType)));
	return r;
}

static int pack_can_0x35e_ACC_35E(can_obj_changan_cs55_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* ACC_CheckSum_id35E: start-bit 63, length 8, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x35e_ACC_35E.ACC_CheckSum_id35E)) & 0xff;
	m |= x;
	/* ACC_RollingCounter_id35E: start-bit 51, length 4, endianess motorola, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x35e_ACC_35E.ACC_RollingCounter_id35E)) & 0xf;
	x <<= 8; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x35e_ACC_35E_tx = 1;
	return 0;
}

static int unpack_can_0x35e_ACC_35E(can_obj_changan_cs55_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* ACC_CheckSum_id35E: start-bit 63, length 8, endianess motorola, scaling 1, offset 0 */
	x = m & 0xff;
	o->can_0x35e_ACC_35E.ACC_CheckSum_id35E = x;
	/* ACC_RollingCounter_id35E: start-bit 51, length 4, endianess motorola, scaling 1, offset 0 */
	x = (m >> 8) & 0xf;
	o->can_0x35e_ACC_35E.ACC_RollingCounter_id35E = x;
	o->can_0x35e_ACC_35E_rx = 1;
	o->can_0x35e_ACC_35E_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x35e_ACC_CheckSum_id35E(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x35e_ACC_35E.ACC_CheckSum_id35E);
	if (rval <= 254) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8_t)0;
		return -1;
	}
}

int encode_can_0x35e_ACC_CheckSum_id35E(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x35e_ACC_35E.ACC_CheckSum_id35E = 0;
	if (in > 254)
		return -1;
	o->can_0x35e_ACC_35E.ACC_CheckSum_id35E = in;
	return 0;
}

int decode_can_0x35e_ACC_RollingCounter_id35E(const can_obj_changan_cs55_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x35e_ACC_35E.ACC_RollingCounter_id35E);
	*out = rval;
	return 0;
}

int encode_can_0x35e_ACC_RollingCounter_id35E(can_obj_changan_cs55_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x35e_ACC_35E.ACC_RollingCounter_id35E = in;
	return 0;
}

int print_can_0x35e_ACC_35E(const can_obj_changan_cs55_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, printf("ACC_CheckSum_id35E = (wire: %.0f)\n", (double)(o->can_0x35e_ACC_35E.ACC_CheckSum_id35E)));
	r = print_helper(r, printf("ACC_RollingCounter_id35E = (wire: %.0f)\n", (double)(o->can_0x35e_ACC_35E.ACC_RollingCounter_id35E)));
	return r;
}

int unpack_message(can_obj_changan_cs55_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(dlc <= 8);         /* Maximum of 8 bytes in a CAN packet */
	switch (id) {
	case 0x208: return unpack_can_0x208_P_Can2_208(o, data, dlc, time_stamp);
	case 0x218: return unpack_can_0x218_EPBi_218(o, data, dlc, time_stamp);
	case 0x24e: return unpack_can_0x24e_ACC_24E(o, data, dlc, time_stamp);
	case 0x255: return unpack_can_0x255_EMS_255(o, data, dlc, time_stamp);
	case 0x258: return unpack_can_0x258_P_Can1_258(o, data, dlc, time_stamp);
	case 0x25e: return unpack_can_0x25e_ACC_25E(o, data, dlc, time_stamp);
	case 0x278: return unpack_can_0x278_EPBi_278(o, data, dlc, time_stamp);
	case 0x2a0: return unpack_can_0x2a0_EPS_2A0(o, data, dlc, time_stamp);
	case 0x2a1: return unpack_can_0x2a1_EPS_2A1(o, data, dlc, time_stamp);
	case 0x2a8: return unpack_can_0x2a8_APA_ParkNoticeInfo_2A8(o, data, dlc, time_stamp);
	case 0x35e: return unpack_can_0x35e_ACC_35E(o, data, dlc, time_stamp);
	default: break; 
	}
	return -1; 
}

int pack_message(can_obj_changan_cs55_h_t *o, const unsigned long id, uint64_t *data) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	switch (id) {
	case 0x208: return pack_can_0x208_P_Can2_208(o, data);
	case 0x218: return pack_can_0x218_EPBi_218(o, data);
	case 0x24e: return pack_can_0x24e_ACC_24E(o, data);
	case 0x255: return pack_can_0x255_EMS_255(o, data);
	case 0x258: return pack_can_0x258_P_Can1_258(o, data);
	case 0x25e: return pack_can_0x25e_ACC_25E(o, data);
	case 0x278: return pack_can_0x278_EPBi_278(o, data);
	case 0x2a0: return pack_can_0x2a0_EPS_2A0(o, data);
	case 0x2a1: return pack_can_0x2a1_EPS_2A1(o, data);
	case 0x2a8: return pack_can_0x2a8_APA_ParkNoticeInfo_2A8(o, data);
	case 0x35e: return pack_can_0x35e_ACC_35E(o, data);
	default: break; 
	}
	return -1; 
}

int print_message(const can_obj_changan_cs55_h_t *o, const unsigned long id, FILE *output) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(output);
	switch (id) {
	case 0x208: return print_can_0x208_P_Can2_208(o, output);
	case 0x218: return print_can_0x218_EPBi_218(o, output);
	case 0x24e: return print_can_0x24e_ACC_24E(o, output);
	case 0x255: return print_can_0x255_EMS_255(o, output);
	case 0x258: return print_can_0x258_P_Can1_258(o, output);
	case 0x25e: return print_can_0x25e_ACC_25E(o, output);
	case 0x278: return print_can_0x278_EPBi_278(o, output);
	case 0x2a0: return print_can_0x2a0_EPS_2A0(o, output);
	case 0x2a1: return print_can_0x2a1_EPS_2A1(o, output);
	case 0x2a8: return print_can_0x2a8_APA_ParkNoticeInfo_2A8(o, output);
	case 0x35e: return print_can_0x35e_ACC_35E(o, output);
	default: break; 
	}
	return -1; 
}

