// Generated by gencpp from file robot_msgs/Head.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_HEAD_H
#define ROBOT_MSGS_MESSAGE_HEAD_H

#include <ros/service_traits.h>


#include <robot_msgs/HeadRequest.h>
#include <robot_msgs/HeadResponse.h>


namespace robot_msgs
{

struct Head
{

typedef HeadRequest Request;
typedef HeadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Head
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::Head > {
  static const char* value()
  {
    return "692066f040717cc8522264699ee67211";
  }

  static const char* value(const ::robot_msgs::Head&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::Head > {
  static const char* value()
  {
    return "robot_msgs/Head";
  }

  static const char* value(const ::robot_msgs::Head&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::HeadRequest> should match 
// service_traits::MD5Sum< ::robot_msgs::Head > 
template<>
struct MD5Sum< ::robot_msgs::HeadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::Head >::value();
  }
  static const char* value(const ::robot_msgs::HeadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::HeadRequest> should match 
// service_traits::DataType< ::robot_msgs::Head > 
template<>
struct DataType< ::robot_msgs::HeadRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::Head >::value();
  }
  static const char* value(const ::robot_msgs::HeadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::HeadResponse> should match 
// service_traits::MD5Sum< ::robot_msgs::Head > 
template<>
struct MD5Sum< ::robot_msgs::HeadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::Head >::value();
  }
  static const char* value(const ::robot_msgs::HeadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::HeadResponse> should match 
// service_traits::DataType< ::robot_msgs::Head > 
template<>
struct DataType< ::robot_msgs::HeadResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::Head >::value();
  }
  static const char* value(const ::robot_msgs::HeadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_HEAD_H
