// Generated by gencpp from file robot_msgs/HeadResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_HEADRESPONSE_H
#define ROBOT_MSGS_MESSAGE_HEADRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct HeadResponse_
{
  typedef HeadResponse_<ContainerAllocator> Type;

  HeadResponse_()
    : x(0)
    , y(0)
    , error(0)  {
    }
  HeadResponse_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , error(0)  {
  (void)_alloc;
    }



   typedef uint32_t _x_type;
  _x_type x;

   typedef uint32_t _y_type;
  _y_type y;

   typedef uint8_t _error_type;
  _error_type error;




  typedef boost::shared_ptr< ::robot_msgs::HeadResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::HeadResponse_<ContainerAllocator> const> ConstPtr;

}; // struct HeadResponse_

typedef ::robot_msgs::HeadResponse_<std::allocator<void> > HeadResponse;

typedef boost::shared_ptr< ::robot_msgs::HeadResponse > HeadResponsePtr;
typedef boost::shared_ptr< ::robot_msgs::HeadResponse const> HeadResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::HeadResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::HeadResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'robot_msgs': ['/home/renxl/share/catkin_ws/src/ihome/robot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::HeadResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::HeadResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::HeadResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::HeadResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::HeadResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::HeadResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::HeadResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d51d044da01cbcfb0570e12b1866ce6f";
  }

  static const char* value(const ::robot_msgs::HeadResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd51d044da01cbcfbULL;
  static const uint64_t static_value2 = 0x0570e12b1866ce6fULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::HeadResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/HeadResponse";
  }

  static const char* value(const ::robot_msgs::HeadResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::HeadResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 x\n\
uint32 y\n\
uint8 error\n\
\n\
";
  }

  static const char* value(const ::robot_msgs::HeadResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::HeadResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HeadResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::HeadResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::HeadResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.y);
    s << indent << "error: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_HEADRESPONSE_H
