// Generated by gencpp from file robot_msgs/Speak.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_SPEAK_H
#define ROBOT_MSGS_MESSAGE_SPEAK_H

#include <ros/service_traits.h>


#include <robot_msgs/SpeakRequest.h>
#include <robot_msgs/SpeakResponse.h>


namespace robot_msgs
{

struct Speak
{

typedef SpeakRequest Request;
typedef SpeakResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Speak
} // namespace robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_msgs::Speak > {
  static const char* value()
  {
    return "ffe2ed0131a0c7d14cc080adec6a4104";
  }

  static const char* value(const ::robot_msgs::Speak&) { return value(); }
};

template<>
struct DataType< ::robot_msgs::Speak > {
  static const char* value()
  {
    return "robot_msgs/Speak";
  }

  static const char* value(const ::robot_msgs::Speak&) { return value(); }
};


// service_traits::MD5Sum< ::robot_msgs::SpeakRequest> should match 
// service_traits::MD5Sum< ::robot_msgs::Speak > 
template<>
struct MD5Sum< ::robot_msgs::SpeakRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::Speak >::value();
  }
  static const char* value(const ::robot_msgs::SpeakRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::SpeakRequest> should match 
// service_traits::DataType< ::robot_msgs::Speak > 
template<>
struct DataType< ::robot_msgs::SpeakRequest>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::Speak >::value();
  }
  static const char* value(const ::robot_msgs::SpeakRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_msgs::SpeakResponse> should match 
// service_traits::MD5Sum< ::robot_msgs::Speak > 
template<>
struct MD5Sum< ::robot_msgs::SpeakResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_msgs::Speak >::value();
  }
  static const char* value(const ::robot_msgs::SpeakResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_msgs::SpeakResponse> should match 
// service_traits::DataType< ::robot_msgs::Speak > 
template<>
struct DataType< ::robot_msgs::SpeakResponse>
{
  static const char* value()
  {
    return DataType< ::robot_msgs::Speak >::value();
  }
  static const char* value(const ::robot_msgs::SpeakResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_SPEAK_H
