// Generated by gencpp from file robot_msgs/SpeekResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_SPEEKRESPONSE_H
#define ROBOT_MSGS_MESSAGE_SPEEKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_msgs
{
template <class ContainerAllocator>
struct SpeekResponse_
{
  typedef SpeekResponse_<ContainerAllocator> Type;

  SpeekResponse_()
    : code(0)  {
    }
  SpeekResponse_(const ContainerAllocator& _alloc)
    : code(0)  {
  (void)_alloc;
    }



   typedef uint32_t _code_type;
  _code_type code;




  typedef boost::shared_ptr< ::robot_msgs::SpeekResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::SpeekResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SpeekResponse_

typedef ::robot_msgs::SpeekResponse_<std::allocator<void> > SpeekResponse;

typedef boost::shared_ptr< ::robot_msgs::SpeekResponse > SpeekResponsePtr;
typedef boost::shared_ptr< ::robot_msgs::SpeekResponse const> SpeekResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::SpeekResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::SpeekResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'robot_msgs': ['/home/renxl/share/catkin_ws/src/ihome/robot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::SpeekResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::SpeekResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::SpeekResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::SpeekResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::SpeekResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::SpeekResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::SpeekResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d996991b911ad3473a76f58f16c28fc";
  }

  static const char* value(const ::robot_msgs::SpeekResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d996991b911ad34ULL;
  static const uint64_t static_value2 = 0x73a76f58f16c28fcULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::SpeekResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/SpeekResponse";
  }

  static const char* value(const ::robot_msgs::SpeekResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::SpeekResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 code\n\
\n\
";
  }

  static const char* value(const ::robot_msgs::SpeekResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::SpeekResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpeekResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::SpeekResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::SpeekResponse_<ContainerAllocator>& v)
  {
    s << indent << "code: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_SPEEKRESPONSE_H
